apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-gateway-service-5ba74e6ab6fdcfaf32766f041617d473a7842e55
    digest: sha256:a44a4956fe2435697264fa6dc7be8e86a99a262a87a423f7810ae12468c4f05a
