apiVersion: v1
kind: ConfigMap
metadata:
  name: fundit-project-config
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-project
    app.kubernetes.io/part-of: fundit
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  MEDIA_S3_BUCKET: fundit-media-dev-team6
  AWS_REGION: ap-northeast-2
  INVENTORY_CLIENT_MODE: http
  ORDER_SERVICE_BASE_URL: http://fundit-order-svc:8080
  SPRING_FLYWAY_DEFAULT_SCHEMA: project
  SPRING_FLYWAY_SCHEMAS: project
  SPRING_FLYWAY_CREATE_SCHEMAS: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: project
