apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-project-service-02c105d1257b2c96877234bfaf429d02fa33fc09
    digest: sha256:ab5f238e4fe0d6bac37d355a03f4312469e6b4630ff2d969878931a509e74791
