apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-project-service-e6a1c773d2528e83e1a3cd803e983162ac736573
    digest: sha256:b99f28d293810bedd67e41201b41e4ee0fa5b2a6194a9895ebcb5e954b67d3ef
