apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-project-service-0828aa648321bab0ad5ad138d5b5ca1e74a18d4e
    digest: sha256:654b9c47aed3b8b0abc43f5baa907f04639856e096390e3e12ce761e724e62f9
