apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-copilot
    newTag: sha-4b5b7c70251bd4124b36e1a212945f3ef29ccd08
    digest: sha256:6b241c1d630f070e11422ce08fa2c52cf563a074a8f05abcdfeaf0e7ed502d7e
