apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-copilot
    newTag: sha-302ee79945b6883f23d58c1b2380e86f5a99bbfa
    digest: sha256:fd187a020a1b7b80485e132a06e2ccf76c3c52d903f73b89e1d024b32e5fc17a
