apiVersion: v1
kind: Service
metadata:
  name: fundit-ai-copilot-svc
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-ai-copilot
    app.kubernetes.io/part-of: fundit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fundit-ai-copilot
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
