apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-payment-service-5ba74e6ab6fdcfaf32766f041617d473a7842e55
    digest: sha256:4201054c62d6014ba188f5d126273601bf1c8844ecd97d77bc74a46b9d2f9e19
