apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-payment-service-f127a6ff359772ae6dde6811a79a9d9844a532d1
    digest: sha256:d9be1bb2029e7c54bc40401d9d6572a28f4e2e17ff46783c0866b8a041c8105c
