apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-live-service-80fb8d2fe319675944cce1d48db6b80cdf55f3eb
    digest: sha256:ece8e2d047607b7ea48ea0218d52f213e40c58b2cbd39932dd4ca7e1851c465b
