apiVersion: v1
kind: Service
metadata:
  name: fundit-live-svc
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-live
    app.kubernetes.io/part-of: fundit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fundit-live
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
