apiVersion: v1
kind: ServiceAccount
metadata:
  name: fundit-live-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-live
    app.kubernetes.io/part-of: fundit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::899957568205:role/FunditLiveIvsRole-fundit-dev-eks
automountServiceAccountToken: false
