apiVersion: v1
kind: ServiceAccount
metadata:
  name: fundit-live-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-live
    app.kubernetes.io/part-of: fundit
  annotations:
    # Infra Terraform이 생성하는 Live 전용 IVS/IVS Chat IRSA Role ARN이다.
    eks.amazonaws.com/role-arn: arn:aws:iam::899957568205:role/fundit-dev-live-ivs-role
automountServiceAccountToken: true
