apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-auth-service-f7e5236b1ce70f1c7b56065706659ae0f6158ecb
    digest: sha256:a8fe0d4065a70dbc1fe81255f1b4c73eadde736bae9a89322ec39f666d7634f0
