apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-auth-service-4e40800bedbff7087a0efae6727a07c45048e41c
    digest: sha256:d7754645b30bb131fe606ea9f7a526dd5033bd5e5f7ee49522acf5635854ada8
