apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-auth-service-e6a1c773d2528e83e1a3cd803e983162ac736573
    digest: sha256:d09717a763b247f94a2c80b22ddb73cbb2c679606e21d908f548729c4e75dfe2
