apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-cuesheet
    newTag: sha-21d01d90a25b41dc336b2ce922a184dc489ff98d
    digest: sha256:4925adf7027f0d0e514471d90a8e9e470d96c55e608d3a07ec77020cf610499a
