apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-cuesheet
    newTag: sha-08d7dc6bfab6005820f5adf4dff04c66f9efc7a7
    digest: sha256:308f6384d4f1812700d9e632cfb02f733e191b1241cf114d4f54cad3ad77c2f5
