apiVersion: v1
kind: Service
metadata:
  name: fundit-ai-cuesheet-svc
  namespace: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8420"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: fundit-ai-cuesheet
    app.kubernetes.io/part-of: fundit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fundit-ai-cuesheet
  ports:
    - name: http
      port: 8420
      targetPort: http
      protocol: TCP
