apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-services-metrics
  namespace: dev
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - fundit-auth
          - fundit-fulfillment
          - fundit-live
          - fundit-member
          - fundit-notification
          - fundit-order
          - fundit-payment
          - fundit-project
          - fundit-search
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ai-services-metrics
  namespace: dev
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - fundit-ai-copilot
          - fundit-ai-cuesheet
          - fundit-ai-highlight
          - fundit-ai-funding-story
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
