apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-member-service-5ba74e6ab6fdcfaf32766f041617d473a7842e55
    digest: sha256:9826b6d70651bfe867023470163e5228ea10954e16043ad5cba8541994adf282
