apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-member-service-e6a1c773d2528e83e1a3cd803e983162ac736573
    digest: sha256:11f9a3462e1b62a7f17e8dd3e5c810310607b0b9385e0c966fe785089029e0f2
