apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-fulfillment-service-31e878cad415b03897614c24ee66171969b3caab
    digest: sha256:902e1ad4823a048a1250ee8b7d30752af8657c6d7a7c577bcfcfefe212160feb
