apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-fulfillment-service-54bad36720dd43b2966c20cb968b6530d60b0f5f
    digest: sha256:956170c9d12f3e01cbfe39f797576a78821cf3726ddc031d2270492c40ab7347
