apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fundit-member-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: fundit-member-secret
    creationPolicy: Orphan
  data:
    - secretKey: member-encryption-key
      remoteRef: {key: fundit/dev/member, property: member-encryption-key}
