apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fundit-dev
  namespace: argocd
spec:
  description: Fundit dev 환경 전용 프로젝트
  sourceRepos:
    - https://github.com/KT-Cloud-Tech-Up-team6/Fundit-GitOps.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: karpenter.sh
      kind: NodePool
    - group: karpenter.k8s.aws
      kind: EC2NodeClass
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"