apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-notification-service-5ba74e6ab6fdcfaf32766f041617d473a7842e55
    digest: sha256:c7a6e6819f5358749bcf061fdefe68f6d0372b2eac65c964ec955da498ca61c0
