apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-notification-service-e8b5e198868911c9ed56003c85ba3616450e0525
    digest: sha256:0a9c9de1ac69bce6a7620bae370cdb92daa3442bcefca21bdb89451131d65cec
