apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-highlight
    newTag: sha-1ad5ded1c6ca93fcf40f7baf3d007c8ac3060325
    digest: sha256:45b87e6edc07d6d2fd7efd80975541e2c383a88efbaab70798a47b873382cb5a
