apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-ai-highlight
    newTag: sha-69d02188a61e91341dda9c9587d6958399c727ab
    digest: sha256:9bb75e7114a94438e67783b0b4a85d163122b6bdf3faee1cce5ecc5442a83c27
