apiVersion: v1
kind: ServiceAccount
metadata:
  name: fundit-ai-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-ai-highlight
    app.kubernetes.io/part-of: fundit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::899957568205:role/fundit-dev-ai-s3-role
automountServiceAccountToken: true
