apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-order-service-54bad36720dd43b2966c20cb968b6530d60b0f5f
    digest: sha256:2254c1f1a58ba5c4ab2e5e91128fc952896b16ce9c9fd6fb05be0a31ef086d17
