apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-order-service-d8f64fd6c725fda29f4cd15a8b2e450406a14803
    digest: sha256:1ee55172304d178d8ed563684a00f5834939053f14780a8a7de79c5c8786a8b3
