apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-order-service-4e40800bedbff7087a0efae6727a07c45048e41c
    digest: sha256:290027692b932e8dc05ad48763533d5134912181e7074547dcae9883e8fb5a79
