apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-frontend
    newTag: sha-78d90fd04c1402678d8ee2bd18626652f017e7be
    digest: sha256:382eb3ad246dbe9cbf2a101b45cd518f5abf83be9f2a30fdb834529bec54eaf6
