apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-frontend
    newTag: sha-cc96ef1d8ba316bb383dc9ca9b659d9e52c01408
    digest: sha256:e9a8cf3b18b554483d7fe01a7fce3e6670542255431cde2fcef5cfdbad71a3cd
