apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-frontend
    newTag: sha-10d5b462a0e15abac0a1e7ab9e2d7bc4cb5dfba6
    digest: sha256:b79a048d1c74d444ba6340db780cbbf8c2658c4108531d15bd09566ca65d9d29
