apiVersion: v1
kind: Service
metadata:
  name: fundit-backend-svc
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-gateway
    app.kubernetes.io/part-of: fundit
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fundit-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
