apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../worker-base

nameSuffix: -funding-story
labels:
  - pairs:
      app.kubernetes.io/instance: funding-story
    includeSelectors: true
