apiVersion: v1
kind: ConfigMap
metadata:
  name: fundit-search-config
  namespace: dev
  labels:
    app.kubernetes.io/name: fundit-search
    app.kubernetes.io/part-of: fundit
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  SPRING_FLYWAY_DEFAULT_SCHEMA: search
  SPRING_FLYWAY_SCHEMAS: search
  SPRING_FLYWAY_CREATE_SCHEMAS: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: search
