apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-search-service-f8be5ffda8c7f5d3208f4f9ba6d8557ab54bab76
    digest: sha256:f57c8fdc6f5c3a7e72617ac9668b7d988cf87bc042242702ed3947b22890036530
