apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: 899957568205.dkr.ecr.ap-northeast-2.amazonaws.com/fundit-backend
    newTag: sha-search-service-e6a1c773d2528e83e1a3cd803e983162ac736573
    digest: sha256:dddf822517547f71eb23d91c15063fdd150a7b9ebd4b1bdd9071c01348d7f130
