apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ai-cuesheet
  - ai-highlight
  - auth
  - fulfillment
  - live
  - member
  - notification
  - order
  - payment
  - project
  - search
