apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../worker-base

nameSuffix: -page-summary
labels:
  - pairs:
      app.kubernetes.io/instance: page-summary
    includeSelectors: true
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: page-summary
